on:
  push:
    branches:
    - main
    - release/*
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        output_file: "diagram.svg"
        should_push: false
        artifact_name: "artifact"
